categories/urls.py
from django.urls import path
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView

from .models import Category

category_fields = ['name', 'description', 'image', 'parent']

app_name = 'categories'
urlpatterns = [
    path('', ListView.as_view(model=Category), name="category_list",),
    path('detail/<int:pk>', DetailView.as_view(model=Category), name="category_detail"),
    path('update/<int:pk>', UpdateView.as_view(model=Category), name="category_update"),
    path('delete/<int:pk>', DeleteView.as_view(model=Category, success_url='/'), name="category_delete"),
    path('create/', CreateView.as_view(model=Category, fields = category_fields), name="category_create"),
]

homework/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('categories.urls'), name='categories'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

categories/models.py
from django.urls import reverse
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey

from .validators import validate_max_instance


class Category(MPTTModel):
    name = models.CharField(max_length=50)
    description = models.TextField()
    image = models.ImageField(upload_to="images")
    parent = TreeForeignKey('self', on_delete=models.CASCADE, blank=True, null=True, related_name='children')

    def clean(self):
        validate_max_instance(self)

    def get_absolute_url(self):
        return reverse('categories:category_list')

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

categories/views.py
from django.shortcuts import render

# Create your views here.

categories/templates/categories/category_confirm_delete.html
<h1>Delete?</h1>
<form action="" method="post">
    {% csrf_token %}
    <button>yes</button>
    <button><a href="javascript:history.back()">back</a></button>
</form>

categories/templates/categories/category_detail.html
<h1>Category: {{ object.name }}</h1>
<p>Description: {{ object.description }}</p>
<p>Parent: {{ object.parent }}</p>
<img style="width:300px; height:250px;" src="{{object.image.url}}" alt="">
<button><a href="javascript:history.back()">back</a></button>

categories/templates/categories/category_form.html
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_ul }}
    <button>save</button>
    <button><a href="javascript:history.back()">back</a></button>
</form>

categories/templates/categories/category_list.html
{% load mptt_tags %}

<ul class="root">
    {% recursetree object_list %}
        <li>
            {{ node.name }} <a href="{% url 'categories:category_delete' node.pk %}">remove</a> <a href="{% url 'categories:category_detail' node.pk %}">detail</a>
            {% if not node.is_leaf_node %}
                <ul class="children">
                    {{ children }}
                </ul>
            {% endif %}
        </li>
    {% endrecursetree %}
</ul>

<a href={% url 'categories:category_create' %}>add new Category</a>